# Generated by Django 5.2.2 on 2025-06-07 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('experience', models.IntegerField(verbose_name='Стаж работы (лет)')),
                ('driver_class', models.CharField(choices=[('1', 'Первый класс'), ('2', 'Второй класс'), ('3', 'Третий класс')], max_length=1, verbose_name='Классность')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.driver', verbose_name='Напарник')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('company', models.CharField(max_length=50, verbose_name='Фирма')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('load_capacity', models.FloatField(verbose_name='Грузоподъемность (тонн)')),
                ('fuel_consumption', models.FloatField(verbose_name='Расход топлива (л/100 км)')),
                ('trailer_length', models.FloatField(verbose_name='Длина прицепа (м)')),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость перевозки (руб/км)')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Трейлер',
                'verbose_name_plural': 'Трейлеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заказа')),
                ('weight', models.FloatField(verbose_name='Вес (тонн)')),
                ('items_count', models.IntegerField(verbose_name='Количество мест')),
                ('departure_point', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('destination_point', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('distance', models.FloatField(verbose_name='Расстояние (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.driver', verbose_name='Водитель')),
                ('trailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.trailer', verbose_name='Трейлер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
