# Generated by Django 5.2.2 on 2025-06-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['full_name'], 'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['brand'], 'verbose_name': 'Трейлер', 'verbose_name_plural': 'Трейлеры'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='Стаж работы (лет)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расстояние (км)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_count',
            field=models.PositiveIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вес груза (тонн)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='cost_per_km',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Стоимость перевозки (руб/км)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.driver', verbose_name='Основной водитель'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Расход топлива (л/100 км)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='load_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Грузоподъемность (тонн)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина прицепа (м)'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['departure_point', 'destination_point'], name='transports__departu_d59d39_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='transports__created_ec0983_idx'),
        ),
    ]
